name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          working_directory: thesis-pytorch-hybrid-fuzzing/thesis-src
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.aux
          working_directory: thesis-pytorch-hybrid-fuzzing/thesis-src
          compiler: bibtex
          args:
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          working_directory: thesis-pytorch-hybrid-fuzzing/thesis-src
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: thesis-pytorch-hybrid-fuzzing/thesis.pdf
